name: 'data_infused_dbt'
version: '1.0.0'

profile: 'data_infused_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_infused_dbt:
    01_staging:
      +materialized: view
      +schema: staging
    02_intermediate:
      +materialized: table
      +schema: intermediate
    03_marts:
    +materialized: table
    +schema: marts