name: dbt CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: ./data_infused_dbt
      DBT_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      DBT_ROLE: ${{ secrets.DBT_ROLE }}
      DBT_DATABASE: ${{ secrets.DBT_DATABASE }}
      DBT_WAREHOUSE: ${{ secrets.DBT_WAREHOUSE }}
      DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake sqlfluff
          pip install sqlfluff
          pip install sqlfluff-templater-dbt

      - name: List files in profiles dir
        run: ls -l data_infused_dbt

      - name: Show profiles.yml
        run: cat data_infused_dbt/profiles.yml

      - name: Run dbt debug
        run: dbt debug --project-dir data_infused_dbt --profiles-dir data_infused_dbt

      - name: Run dbt tests
        run: dbt test --project-dir data_infused_dbt --profiles-dir data_infused_dbt

      - name: Run SQLFluff lint
        run: sqlfluff lint models --dialect snowflake
        working-directory: ${{ env.PROJECT_DIR }}