name: dbt CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake sqlfluff

      - name: Run dbt debug
        run: dbt debug --project-dir dbt --profiles-dir dbt

      - name: Run dbt tests
        run: dbt test --project-dir dbt --profiles-dir dbt

      - name: Run SQLFluff lint
        run: sqlfluff lint dbt/models
